#!/usr/bin/env bash
#SBATCH --job-name=guacamol_theta_tasks
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
#SBATCH --time=24:00:00
#SBATCH --array=0-19%20
#SBATCH --output=slurm-%x-%A_%a.out
#SBATCH --error=slurm-%x-%A_%a.err

set -euo pipefail

# Run SpectralMol theta-only GuacaMol as a Slurm task array.
# Each array element runs one GuacaMol task. Default is one theta-only seed.
# Override SEEDS/MOLSCORE_PARALLEL_JOBS/--cpus-per-task for multi-restart runs.

TASKS=(
  "Celecoxib_rediscovery"
  "Troglitazone_rediscovery"
  "Thiothixene_rediscovery"
  "Aripiprazole_similarity"
  "Albuterol_similarity"
  "Mestranol_similarity"
  "C11H24"
  "C9H10N2O2PF2Cl"
  "Median_molecules_1"
  "Median_molecules_2"
  "Osimertinib_MPO"
  "Fexofenadine_MPO"
  "Ranolazine_MPO"
  "Perindopril_MPO"
  "Amlodipine_MPO"
  "Sitagliptin_MPO"
  "Zaleplon_MPO"
  "Valsartan_smarts"
  "Deco_hop"
  "Scaffold_hop"
)

MOLSCORE_TASK_INDEXES=(
  14
  15
  19
  13
  11
  18
  16
  6
  7
  5
  2
  12
  1
  4
  8
  9
  0
  3
  17
  10
)

TASK_INDEX="${SLURM_ARRAY_TASK_ID:-0}"
if (( TASK_INDEX < 0 || TASK_INDEX >= ${#TASKS[@]} )); then
  echo "[error] SLURM_ARRAY_TASK_ID=${TASK_INDEX} outside 0-$((${#TASKS[@]} - 1))" >&2
  exit 1
fi

TASK_NAME="${TASKS[$TASK_INDEX]}"
MOLSCORE_TASK_INDEX="${MOLSCORE_TASK_INDEXES[$TASK_INDEX]}"
SCRIPT_PATH="${BASH_SOURCE[0]:-$0}"
SOURCE_DIR="$(cd "$(dirname "${SCRIPT_PATH}")" && pwd)"
SCRIPT_DIR="${SLURM_SUBMIT_DIR:-${SOURCE_DIR}}"
USER_NAME="${USER:-$(id -un 2>/dev/null || printf user)}"

set_default() {
  local name="$1"
  local value="$2"
  if [[ -z "${!name+x}" || -z "${!name}" ]]; then
    export "${name}=${value}"
  fi
}

auto_profile_for_task() {
  case "${TASK_NAME}" in
    Celecoxib_rediscovery|Troglitazone_rediscovery|Thiothixene_rediscovery|Aripiprazole_similarity)
      printf "target_jump_macro"
      ;;
    Albuterol_similarity)
      printf "macro_heavy_token_off"
      ;;
    Mestranol_similarity)
      printf "target_jump_macro_no_fallback"
      ;;
    C11H24)
      printf "formula_k2"
      ;;
    C9H10N2O2PF2Cl)
      printf "formula_macro"
      ;;
    Osimertinib_MPO)
      printf "mpo_legacy_seedmacro"
      ;;
    Fexofenadine_MPO)
      printf "mpo_target_analog_strong"
      ;;
    Perindopril_MPO)
      printf "mpo_property_explore"
      ;;
    Amlodipine_MPO)
      printf "mpo_target_analog_strong"
      ;;
    Ranolazine_MPO)
      printf "mpo_legacy_seedmacro"
      ;;
    Sitagliptin_MPO)
      printf "mpo_target_analog_balanced"
      ;;
    Median_molecules_1)
      printf "median_balanced"
      ;;
    Median_molecules_2)
      printf "median2_explore"
      ;;
    Zaleplon_MPO)
      printf "mpo_legacy_target_jump_light"
      ;;
    *_MPO)
      printf "mpo_seedmacro"
      ;;
    *_similarity|*_rediscovery)
      printf "macro_heavy"
      ;;
    Median_molecules_*)
      printf "median_balanced"
      ;;
    Valsartan_smarts)
      printf "smarts_target_jump"
      ;;
    Deco_hop|Scaffold_hop)
      printf "scaffold_explore"
      ;;
    *)
      printf "balanced"
      ;;
  esac
}

apply_task_profile_defaults() {
  local profile="$1"

  # Shared theta-only baseline.
  set_default MOLSCORE_SPECTRAL_ENABLE_SEED_MACROS 1
  set_default MOLSCORE_SPECTRAL_SEED_MACRO_MIN_N 3
  set_default MOLSCORE_SPECTRAL_SEED_MACRO_MIN_ATOMS 3
  set_default MOLSCORE_SPECTRAL_SEED_MACRO_MIN_FREQUENCY 1
  set_default MOLSCORE_SPECTRAL_ENABLE_TASK_TARGET_MACROS 1
  set_default MOLSCORE_SPECTRAL_ENABLE_TASK_TARGET_FULL_MACROS 1
  set_default MOLSCORE_SPECTRAL_TASK_TARGET_FULL_MACRO_MAX 16
  set_default MOLSCORE_SPECTRAL_USE_STANDARD_GUACAMOL_TARGETS 1
  set_default MOLSCORE_SPECTRAL_TASK_TARGET_MACRO_MAX 256
  set_default MOLSCORE_SPECTRAL_TASK_TARGET_MACRO_MIN_N 2
  set_default MOLSCORE_SPECTRAL_TASK_TARGET_MACRO_MAX_N 18
  set_default MOLSCORE_SPECTRAL_TASK_TARGET_MACRO_MIN_ATOMS 2
  set_default MOLSCORE_SPECTRAL_TASK_TARGET_MACRO_MIN_FREQUENCY 1
  set_default MOLSCORE_SPECTRAL_TASK_TARGET_MACRO_WEIGHT 12
  set_default MOLSCORE_SPECTRAL_ENABLE_TASK_TARGET_WINDOW_MACROS 1
  set_default MOLSCORE_SPECTRAL_TASK_TARGET_WINDOW_MACRO_MAX 128
  set_default MOLSCORE_SPECTRAL_TASK_TARGET_WINDOW_MACRO_MIN_N 2
  set_default MOLSCORE_SPECTRAL_TASK_TARGET_WINDOW_MACRO_MAX_N 12
  set_default MOLSCORE_SPECTRAL_TASK_TARGET_WINDOW_MACRO_MIN_ATOMS 2
  set_default MOLSCORE_SPECTRAL_TASK_TARGET_WINDOW_MACRO_PREFIX TASKW
  set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE 1
  set_default MOLSCORE_SPECTRAL_ELITE_MACRO_SEED_KEEP 256
  set_default SPECTRAL_PHENOTYPE_PROPOSAL_FRACTION 0
  set_default SPECTRAL_BRICS_CROSSOVER_FRACTION 0
  set_default SPECTRAL_BRICS_FRAGMENT_REPLACE_FRACTION 0
  set_default MOLSCORE_THETA_INIT_STD 0.85
  set_default MOLSCORE_CLIP_THETA_NORM 5.0
  set_default MOLSCORE_SPECTRAL_PARENT_MUTATION_STEPS 3
  set_default MOLSCORE_SPECTRAL_IMMIGRANT_MUTATION_STEPS 4
  set_default MOLSCORE_SPECTRAL_THETA_LOCAL_MUTATION_STEPS 1
  set_default MOLSCORE_SPECTRAL_THETA_LOCAL_ROW_RESET_SCALE 0.0
  set_default MOLSCORE_SPECTRAL_THETA_LOCAL_ROW_RESET_SCALES 0.0
  set_default MOLSCORE_SPECTRAL_THETA_LOCAL_MUTATION_STEP_SCHEDULE 1
  set_default MOLSCORE_LOCAL_EVO_MUTATION_STEP_CAP 12
  set_default MOLSCORE_SPECTRAL_ELITE_MACRO_WEIGHT 4
  set_default MOLSCORE_SPECTRAL_REENCODE_POPULATION_AFTER_VOCAB_REFRESH 1
  set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_JUMP_FRACTION 0.03

  case "${profile}" in
    manual|off)
      ;;
    formula_k2)
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 2
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 384
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 12
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 25
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 96
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.65
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.45
      set_default MOLSCORE_GAUSS_STD_THETA 0.22
      set_default MOLSCORE_P_PARAM_NOISE 0.12
      set_default MOLSCORE_P_ROW_RESET 0.012
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.25
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.08
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.15
      ;;
    formula_macro)
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 1
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 768
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 16
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 20
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 128
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.65
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.45
      set_default MOLSCORE_GAUSS_STD_THETA 0.22
      set_default MOLSCORE_P_PARAM_NOISE 0.12
      set_default MOLSCORE_P_ROW_RESET 0.012
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.30
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.08
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.20
      ;;
    mpo_seedmacro)
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 1
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 512
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 14
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 20
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 128
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.70
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.45
      set_default MOLSCORE_GAUSS_STD_THETA 0.22
      set_default MOLSCORE_P_PARAM_NOISE 0.12
      set_default MOLSCORE_P_ROW_RESET 0.012
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.40
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.10
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.30
      ;;
    mpo_seedmacro_token_off)
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 1
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 512
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 14
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 20
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 128
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.70
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.45
      set_default MOLSCORE_GAUSS_STD_THETA 0.22
      set_default MOLSCORE_P_PARAM_NOISE 0.12
      set_default MOLSCORE_P_ROW_RESET 0.012
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.0
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.0
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.0
      ;;
    mpo_token_strong)
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 1
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 512
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 14
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 20
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 128
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.70
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.45
      set_default MOLSCORE_GAUSS_STD_THETA 0.22
      set_default MOLSCORE_P_PARAM_NOISE 0.12
      set_default MOLSCORE_P_ROW_RESET 0.012
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.55
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.15
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_INSERT_PROB 0.25
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_DELETE_PROB 0.06
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.35
      ;;
    mpo_k2_token_light)
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 2
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 384
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 12
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 25
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 96
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.65
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.45
      set_default MOLSCORE_GAUSS_STD_THETA 0.22
      set_default MOLSCORE_P_PARAM_NOISE 0.12
      set_default MOLSCORE_P_ROW_RESET 0.012
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.15
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.04
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.15
      ;;
    macro_heavy)
      set_default SPECTRAL_DECODE_ATTEMPTS 10
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 1
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 768
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 16
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 20
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 128
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.65
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.45
      set_default MOLSCORE_GAUSS_STD_THETA 0.22
      set_default MOLSCORE_P_PARAM_NOISE 0.12
      set_default MOLSCORE_P_ROW_RESET 0.012
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.50
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.12
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.35
      ;;
    target_jump_macro)
      set_default SPECTRAL_DECODE_ATTEMPTS 10
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 1
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 768
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 16
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 20
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 128
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.65
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.45
      set_default MOLSCORE_GAUSS_STD_THETA 0.22
      set_default MOLSCORE_P_PARAM_NOISE 0.12
      set_default MOLSCORE_P_ROW_RESET 0.012
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.55
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.14
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.40
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_INSERT_FRACTION 0.85
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_JUMP_FRACTION 0.12
      ;;
    target_jump_macro_no_fallback)
      set_default SPECTRAL_DECODE_ATTEMPTS 10
      set_default MOLSCORE_SPECTRAL_USE_STANDARD_GUACAMOL_TARGETS 0
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 1
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 768
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 16
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 20
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 128
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.65
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.45
      set_default MOLSCORE_GAUSS_STD_THETA 0.22
      set_default MOLSCORE_P_PARAM_NOISE 0.12
      set_default MOLSCORE_P_ROW_RESET 0.012
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.50
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.12
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.35
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_INSERT_FRACTION 0.75
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_JUMP_FRACTION 0.10
      ;;
    macro_heavy_token_off)
      set_default SPECTRAL_DECODE_ATTEMPTS 10
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 1
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 768
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 16
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 20
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 128
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.65
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.45
      set_default MOLSCORE_GAUSS_STD_THETA 0.22
      set_default MOLSCORE_P_PARAM_NOISE 0.12
      set_default MOLSCORE_P_ROW_RESET 0.012
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.0
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.0
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.0
      ;;
    macro_token_strong)
      set_default SPECTRAL_DECODE_ATTEMPTS 10
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 1
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 768
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 16
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 20
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 128
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.65
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.45
      set_default MOLSCORE_GAUSS_STD_THETA 0.22
      set_default MOLSCORE_P_PARAM_NOISE 0.12
      set_default MOLSCORE_P_ROW_RESET 0.012
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.60
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.15
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_INSERT_PROB 0.25
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_DELETE_PROB 0.05
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.45
      ;;
    median_balanced)
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 1
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 512
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 14
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 20
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 128
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.55
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.55
      set_default MOLSCORE_GAUSS_STD_THETA 0.24
      set_default MOLSCORE_P_PARAM_NOISE 0.14
      set_default MOLSCORE_P_ROW_RESET 0.014
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.30
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.08
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.20
      ;;
    median_token_strong)
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 1
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 512
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 14
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 20
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 128
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.55
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.55
      set_default MOLSCORE_GAUSS_STD_THETA 0.24
      set_default MOLSCORE_P_PARAM_NOISE 0.14
      set_default MOLSCORE_P_ROW_RESET 0.014
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.45
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.12
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_INSERT_PROB 0.25
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_DELETE_PROB 0.08
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.30
      ;;
    median2_explore)
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 2
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 768
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 16
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 15
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 160
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.60
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.55
      set_default MOLSCORE_GAUSS_STD_THETA 0.26
      set_default MOLSCORE_P_PARAM_NOISE 0.16
      set_default MOLSCORE_P_ROW_RESET 0.018
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.55
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.15
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_MAX_EDITS 3
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_INSERT_PROB 0.30
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_DELETE_PROB 0.10
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.40
      set_default MOLSCORE_SPECTRAL_ENABLE_TASK_TARGET_FULL_MACROS 0
      ;;
    smarts_k2)
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 2
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 768
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 16
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 20
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 128
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.55
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.55
      set_default MOLSCORE_GAUSS_STD_THETA 0.24
      set_default MOLSCORE_P_PARAM_NOISE 0.14
      set_default MOLSCORE_P_ROW_RESET 0.014
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.60
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.15
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.40
      ;;
    smarts_target_jump)
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 3
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 1024
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 18
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 15
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 160
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.65
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.55
      set_default MOLSCORE_GAUSS_STD_THETA 0.24
      set_default MOLSCORE_P_PARAM_NOISE 0.14
      set_default MOLSCORE_P_ROW_RESET 0.014
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.75
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.25
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_MAX_EDITS 3
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_INSERT_PROB 0.35
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_DELETE_PROB 0.08
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.55
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_INSERT_FRACTION 0.95
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_JUMP_FRACTION 0.25
      ;;
    mpo_target_jump)
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 1
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 768
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 16
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 20
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 128
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.70
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.45
      set_default MOLSCORE_GAUSS_STD_THETA 0.22
      set_default MOLSCORE_P_PARAM_NOISE 0.12
      set_default MOLSCORE_P_ROW_RESET 0.012
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.45
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.12
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.35
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_INSERT_FRACTION 0.80
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_JUMP_FRACTION 0.10
      ;;
    mpo_target_analog_strong)
      set_default SPECTRAL_DECODE_ATTEMPTS 12
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 2
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 1024
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 18
      set_default MOLSCORE_SPECTRAL_TASK_TARGET_FULL_MACRO_MAX 64
      set_default MOLSCORE_SPECTRAL_TASK_TARGET_WINDOW_MACRO_MAX 256
      set_default MOLSCORE_SPECTRAL_TASK_TARGET_WINDOW_MACRO_MAX_N 14
      set_default MOLSCORE_SPECTRAL_TASK_TARGET_MACRO_MAX 384
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 15
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 192
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.75
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.40
      set_default MOLSCORE_GAUSS_STD_THETA 0.24
      set_default MOLSCORE_P_PARAM_NOISE 0.14
      set_default MOLSCORE_P_ROW_RESET 0.016
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_ANALOG_FRACTION 0.65
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_ANALOG_MUTATION_STEPS 4
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_ANALOG_SIGMA_SCALE 1.15
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.65
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.20
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_MAX_EDITS 3
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_INSERT_PROB 0.32
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_DELETE_PROB 0.10
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.55
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_INSERT_FRACTION 0.75
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_JUMP_FRACTION 0.06
      ;;
    mpo_window_explore)
      set_default SPECTRAL_DECODE_ATTEMPTS 12
      set_default MOLSCORE_SPECTRAL_MPO_DECODE_STYLE druglike
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 3
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 1024
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 18
      set_default MOLSCORE_SPECTRAL_ENABLE_TASK_TARGET_FULL_MACROS 0
      set_default MOLSCORE_SPECTRAL_TASK_TARGET_WINDOW_MACRO_MAX 384
      set_default MOLSCORE_SPECTRAL_TASK_TARGET_WINDOW_MACRO_MAX_N 16
      set_default MOLSCORE_SPECTRAL_TASK_TARGET_MACRO_MAX 512
      set_default MOLSCORE_SPECTRAL_TASK_TARGET_MACRO_MAX_N 16
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 10
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 224
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.78
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.45
      set_default MOLSCORE_GAUSS_STD_THETA 0.27
      set_default MOLSCORE_P_PARAM_NOISE 0.17
      set_default MOLSCORE_P_ROW_RESET 0.020
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_ANALOG_FRACTION 0.20
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_ANALOG_MUTATION_STEPS 6
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_ANALOG_SIGMA_SCALE 1.45
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.80
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.28
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_MAX_EDITS 4
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_INSERT_PROB 0.38
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_DELETE_PROB 0.16
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.65
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_INSERT_FRACTION 0.55
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_JUMP_FRACTION 0.00
      ;;
    mpo_property_explore)
      set_default SPECTRAL_DECODE_ATTEMPTS 14
      set_default MOLSCORE_SPECTRAL_MPO_DECODE_STYLE property
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 3
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 1024
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 18
      set_default MOLSCORE_SPECTRAL_ENABLE_TASK_TARGET_FULL_MACROS 0
      set_default MOLSCORE_SPECTRAL_ENABLE_TASK_TARGET_WINDOW_MACROS 0
      set_default MOLSCORE_SPECTRAL_TASK_TARGET_MACRO_MAX 128
      set_default MOLSCORE_SPECTRAL_TASK_TARGET_MACRO_MAX_N 8
      set_default MOLSCORE_SPECTRAL_TASK_TARGET_MACRO_WEIGHT 4
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 10
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 224
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.80
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.55
      set_default MOLSCORE_GAUSS_STD_THETA 0.30
      set_default MOLSCORE_P_PARAM_NOISE 0.20
      set_default MOLSCORE_P_ROW_RESET 0.025
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_ANALOG_FRACTION 0.0
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.85
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.32
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_MAX_EDITS 4
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_INSERT_PROB 0.42
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_DELETE_PROB 0.18
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.55
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_INSERT_FRACTION 0.15
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_JUMP_FRACTION 0.00
      ;;
    mpo_target_analog_balanced)
      set_default SPECTRAL_DECODE_ATTEMPTS 10
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 2
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 768
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 16
      set_default MOLSCORE_SPECTRAL_TASK_TARGET_FULL_MACRO_MAX 48
      set_default MOLSCORE_SPECTRAL_TASK_TARGET_WINDOW_MACRO_MAX 192
      set_default MOLSCORE_SPECTRAL_TASK_TARGET_WINDOW_MACRO_MAX_N 14
      set_default MOLSCORE_SPECTRAL_TASK_TARGET_MACRO_MAX 320
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 15
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 160
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.72
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.42
      set_default MOLSCORE_GAUSS_STD_THETA 0.23
      set_default MOLSCORE_P_PARAM_NOISE 0.13
      set_default MOLSCORE_P_ROW_RESET 0.014
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_ANALOG_FRACTION 0.45
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_ANALOG_MUTATION_STEPS 3
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_ANALOG_SIGMA_SCALE 1.00
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.55
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.16
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_MAX_EDITS 3
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_INSERT_PROB 0.28
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_DELETE_PROB 0.08
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.45
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_INSERT_FRACTION 0.65
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_JUMP_FRACTION 0.05
      ;;
    mpo_legacy_seedmacro)
      set_default MOLSCORE_SPECTRAL_MPO_DECODE_STYLE legacy
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 1
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 512
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 14
      set_default MOLSCORE_SPECTRAL_ENABLE_TASK_TARGET_WINDOW_MACROS 0
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 20
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 128
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.70
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.45
      set_default MOLSCORE_GAUSS_STD_THETA 0.22
      set_default MOLSCORE_P_PARAM_NOISE 0.12
      set_default MOLSCORE_P_ROW_RESET 0.012
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_ANALOG_FRACTION 0.0
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.40
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.10
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.30
      ;;
    mpo_target_jump_light)
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 1
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 512
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 14
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 20
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 128
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.70
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.45
      set_default MOLSCORE_GAUSS_STD_THETA 0.22
      set_default MOLSCORE_P_PARAM_NOISE 0.12
      set_default MOLSCORE_P_ROW_RESET 0.012
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.35
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.08
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.25
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_INSERT_FRACTION 0.45
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_JUMP_FRACTION 0.04
      ;;
    mpo_legacy_target_jump_light)
      set_default MOLSCORE_SPECTRAL_MPO_DECODE_STYLE legacy
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 1
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 512
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 14
      set_default MOLSCORE_SPECTRAL_ENABLE_TASK_TARGET_WINDOW_MACROS 0
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 20
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 128
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.70
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.45
      set_default MOLSCORE_GAUSS_STD_THETA 0.22
      set_default MOLSCORE_P_PARAM_NOISE 0.12
      set_default MOLSCORE_P_ROW_RESET 0.012
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_ANALOG_FRACTION 0.0
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.35
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.08
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.25
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_INSERT_FRACTION 0.45
      set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_JUMP_FRACTION 0.04
      ;;
    smarts_token_strong)
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 2
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 768
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 16
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 20
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 128
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.55
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.55
      set_default MOLSCORE_GAUSS_STD_THETA 0.24
      set_default MOLSCORE_P_PARAM_NOISE 0.14
      set_default MOLSCORE_P_ROW_RESET 0.014
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.70
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.20
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_MAX_EDITS 3
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_INSERT_PROB 0.30
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_DELETE_PROB 0.10
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.45
      ;;
    scaffold_explore)
      set_default SPECTRAL_DECODE_ATTEMPTS 10
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 1
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 768
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 16
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 20
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 128
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.45
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.60
      set_default MOLSCORE_GAUSS_STD_THETA 0.28
      set_default MOLSCORE_P_PARAM_NOISE 0.16
      set_default MOLSCORE_P_ROW_RESET 0.018
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.55
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.18
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_MAX_EDITS 3
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_INSERT_PROB 0.30
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_DELETE_PROB 0.10
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.40
      ;;
    balanced|*)
      set_default MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES 1
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX 384
      set_default MOLSCORE_SPECTRAL_SEED_MACRO_MAX_N 12
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_REFRESH_EVERY 25
      set_default MOLSCORE_SPECTRAL_ELITE_MACRO_TOP_N 96
      set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SEARCH_FRACTION 0.65
      set_default MOLSCORE_SPECTRAL_THETA_CROSSOVER_PROBABILITY 0.45
      set_default MOLSCORE_GAUSS_STD_THETA 0.22
      set_default MOLSCORE_P_PARAM_NOISE 0.12
      set_default MOLSCORE_P_ROW_RESET 0.012
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MUTATION_FRACTION 0.35
      set_default MOLSCORE_SPECTRAL_THETA_CHILD_TOKEN_MUTATION_FRACTION 0.10
      set_default MOLSCORE_SPECTRAL_THETA_TOKEN_MACRO_INSERT_PROB 0.25
      ;;
  esac

  set_default MOLSCORE_SPECTRAL_THETA_LOCAL_TOP_FRACTION 0.10
  set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SIGMA_SCALE 0.30
  set_default MOLSCORE_SPECTRAL_THETA_LOCAL_PARAM_NOISE_SCALE 0.35
  set_default MOLSCORE_SPECTRAL_THETA_LOCAL_SIGMA_SCALES "${MOLSCORE_SPECTRAL_THETA_LOCAL_SIGMA_SCALE}"
  set_default MOLSCORE_SPECTRAL_THETA_LOCAL_PARAM_NOISE_SCALES "${MOLSCORE_SPECTRAL_THETA_LOCAL_PARAM_NOISE_SCALE}"
  set_default MOLSCORE_SPECTRAL_THETA_BLEND_CROSSOVER_FRACTION 0.25
  set_default MOLSCORE_SPECTRAL_THETA_DIFFERENTIAL_FRACTION 0.15
  set_default MOLSCORE_SPECTRAL_THETA_DIFFERENTIAL_SCALE 0.40
  set_default MOLSCORE_SPECTRAL_THETA_TARGET_MACRO_INSERT_FRACTION 0.75
}

SPECTRAL_TASK_PROFILE_MODE="${SPECTRAL_TASK_PROFILE_MODE:-auto}"
if [[ "${SPECTRAL_TASK_PROFILE_MODE}" == "off" ]]; then
  SPECTRAL_TASK_PROFILE="off"
elif [[ -z "${SPECTRAL_TASK_PROFILE:-}" ]]; then
  if [[ "${SPECTRAL_TASK_PROFILE_MODE}" == "manual" ]]; then
    SPECTRAL_TASK_PROFILE="manual"
  else
    SPECTRAL_TASK_PROFILE="$(auto_profile_for_task)"
  fi
fi
export SPECTRAL_TASK_PROFILE_MODE
export SPECTRAL_TASK_PROFILE
apply_task_profile_defaults "${SPECTRAL_TASK_PROFILE}"

export MODELS="${MODELS:-spectralmol}"
export TASK_INDEXES_CSV="${TASK_INDEXES_CSV:-${MOLSCORE_TASK_INDEX}}"
export INCLUDE_CSV=""
export SEEDS="${SEEDS:-7}"
export GENERATIONS="${GENERATIONS:-500}"
export POPULATION_SIZE="${POPULATION_SIZE:-256}"
export BATCH_SIZE="${BATCH_SIZE:-256}"
TASK_DECODE_CANDIDATES_FOR_BUDGET="${MOLSCORE_SPECTRAL_TASK_AWARE_DECODE_CANDIDATES:-1}"
if ! [[ "${TASK_DECODE_CANDIDATES_FOR_BUDGET}" =~ ^[0-9]+$ ]] || (( TASK_DECODE_CANDIDATES_FOR_BUDGET < 1 )); then
  TASK_DECODE_CANDIDATES_FOR_BUDGET=1
fi
MIN_BUDGET=$((POPULATION_SIZE + BATCH_SIZE * GENERATIONS * TASK_DECODE_CANDIDATES_FOR_BUDGET))
if [[ -z "${BUDGET:-}" ]]; then
  export BUDGET="${MIN_BUDGET}"
elif (( BUDGET < MIN_BUDGET )); then
  echo "[array] increasing BUDGET from ${BUDGET} to ${MIN_BUDGET} to allow ${GENERATIONS} generations"
  export BUDGET="${MIN_BUDGET}"
else
  export BUDGET
fi
export SEED_POOL_SIZE="${SEED_POOL_SIZE:-256}"
export MOLSCORE_PARALLEL_JOBS="${MOLSCORE_PARALLEL_JOBS:-1}"

OUTPUT_BASE_DIR="${OUTPUT_BASE_DIR:-${SCRIPT_DIR}/reproducibility_runs/guacamol_theta_task_array}"
SAFE_TASK_NAME="${TASK_NAME//[^A-Za-z0-9_]/_}"
export OUTPUT_DIR="${OUTPUT_DIR:-${OUTPUT_BASE_DIR}/task_${TASK_INDEX}_${SAFE_TASK_NAME}}"
mkdir -p "${OUTPUT_DIR}"

echo "[array] task_index=${TASK_INDEX} task=${TASK_NAME}"
echo "[array] molscore_task_index=${MOLSCORE_TASK_INDEX}"
echo "[array] profile_mode=${SPECTRAL_TASK_PROFILE_MODE} profile=${SPECTRAL_TASK_PROFILE}"
echo "[array] seeds=${SEEDS} budget=${BUDGET} generations=${GENERATIONS}"
echo "[array] submit_dir=${SLURM_SUBMIT_DIR:-}"
echo "[array] launcher_dir=${SCRIPT_DIR}"
echo "[array] output_dir=${OUTPUT_DIR}"

if [[ ! -f "${SCRIPT_DIR}/sbatch_guacamol_graphga_vs_spectralmol_slurm.sh" ]]; then
  echo "[error] base launcher not found: ${SCRIPT_DIR}/sbatch_guacamol_graphga_vs_spectralmol_slurm.sh" >&2
  echo "[error] run from the repository root or set SLURM_SUBMIT_DIR accordingly." >&2
  exit 1
fi

exec bash "${SCRIPT_DIR}/sbatch_guacamol_graphga_vs_spectralmol_slurm.sh"
