channels:
  - pytorch
  - nvidia
  - rapidsai
  - conda-forge
  - defaults

dependencies:
  # Core runtime
  - python=3.12
  - pip

  # GPU stack target for current container plan
  - cuda-version=12.9
  
  #  # Deep Learning Frameworks (all these frameworks prefer pip instead of conda for CUDA 12)
  # - 'pytorch=*=*cuda*'
  # - 'pytorch-mutex=*=cuda*'
  # - pytorch-cuda
  # - torchvision
  # - torchaudio


  # Scientific Python + chemistry
  # - rapids=26.02
  - numpy
  - pandas
  - scipy
  - joblib
  - tqdm
  - rdkit
  - openbabel

  # Visualization
  - matplotlib
  - seaborn
  - plotly
  - dash
  - streamlit

    # Distributed Computing
  - dask
  - dask-ml
  - dask-sql
  - dask-labextension
  - ray-default
  - ray-tune
  - ray-train


  # Optional but commonly useful in HPC/cluster workflows
  - dask-jobqueue

  # Project-specific Python packages that are usually pip-installed
  - pip:
    - selfies
    - guacamol
    - morfeus-ml
    - molscore
    - streamlit-extras
    - streamlit-plotly-events
    # RAPIDS packages via pip (CUDA 12)
    - --extra-index-url https://pypi.nvidia.com
    - cudf-cu12==26.2.0
    - dask-cudf-cu12==26.2.0
    - cuml-cu12==26.2.0
    - cugraph-cu12==26.2.0
    - nx-cugraph-cu12==26.2.0
    - cuxfilter-cu12==26.2.0
    - cucim-cu12==26.2.0
    - pylibraft-cu12==26.2.0
    - raft-dask-cu12==26.2.0
    - cuvs-cu12==26.2.0
    # pytorch packages via pip (CUDA 12.9)
    - --extra-index-url https://download.pytorch.org/whl/cu129
    - torch==2.10.0 
    - torchvision==0.25.0 
    - torchaudio==2.10.0
 


